name: 🐛 Bug Report
description: File a bug report.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!
  - type: input
    id: scope
    attributes:
      label: Scope
      description: What part of the project does this issue affect?
      placeholder: Describe the scope of the issue.
    validations:
      required: true
  - type: textarea
    id: report
    attributes:
      label: What happened?
      description: Describe the issue and what you expected to happen.
      placeholder: Provide a detailed description of the bug.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Paste any relevant log output here.
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      description: Select the environment(s) where you encountered the issue.
      options:
        - label: Chromium-based
        - label: Firefox
        - label: Safari
        - label: Node.js
        - label: Deno
        - label: Bun
        - label: Other
    validations:
      required: true
  - type: checkboxes
    id: searched
    attributes:
      label: I have searched for existing issues
      description: Have you checked for existing issues that may already cover this request?
      options:
        - label: "Yes"
          required: true
