name: "\U0001F41B Bug Report"
description: File a bug report.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to report a bug!
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Select the scope(s) of the issue.
      multiple: true
      options:
        - bind
        - clean
        - code
        - custom-element
        - eval
        - event
        - extras
        - for
        - html
        - http
        - if
        - internal
        - is
        - markdown
        - mizu
        - model
        - mustache
        - once
        - ref
        - refresh
        - render
        - repo
        - set
        - show
        - skip
        - test
        - text
        - toc
        - unstable
        - www
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Select the environment(s) where you encountered the issue.
      multiple: true
      options:
        - chromium
        - firefox
        - safari
        - node
        - deno
        - bun
        - linux
        - macos
        - windows
        - other
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: What is happening?
      description: Describe the issue and what you expected to happen.
      placeholder: |
        Provide a detailed description of the bug.
        Include screenshots, logs, or any other relevant information.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Minimal reproduction example
      description: Describe how to reproduce the issue.
      placeholder: >
        Provide a minimal example to reproduce the issue.

        Failure to do so may result in the issue being closed without
        investigation.
      render: html
    validations:
      required: true
  - type: dropdown
    id: i-did-my-homework
    attributes:
      label: I have searched for existing issues
      description: You confirm that you took the time to search for existing issues.
      options:
        - ""
        - "Yes"
    validations:
      required: true
