name: ✨ Feature Request
description: Request a new feature.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to request a feature!
  - type: input
    id: scope
    attributes:
      label: Scope
      description: What part of the project does this issue affect?
      placeholder: Describe the scope of the issue.
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: What do you want to happen?
      description: Describe the feature you would like to see added.
      placeholder: Provide a detailed description of the feature.
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Prior Art
      description: Are there any examples of this feature in other projects?
      placeholder: Provide links to any relevant resources.
    validations:
      required: true
  - type: checkboxes
    id: searched
    attributes:
      label: I have searched for existing issues
      description: Have you checked for existing issues that may already cover this request?
      options:
        - label: "Yes"
          required: true
