name: "\U0001F4DC Spec definition"
description: Propose a new specification.
labels:
  - spec
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to propose a new specification!
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Select the scope(s) of the issue.
      multiple: true
      options:
        - bind
        - clean
        - code
        - coverage
        - custom-element
        - eval
        - event
        - for
        - html
        - http
        - if
        - internal
        - is
        - markdown
        - mizu
        - model
        - mustache
        - once
        - ref
        - refresh
        - render
        - set
        - show
        - skip
        - test
        - text
        - toc
        - unstable
        - www
        - repo
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: What do you want to define?
      description: Describe the specification you would like to see added.
      placeholder: |
        Provide a detailed description of the specification.
        Include diagrams, examples, or any other relevant information.
    validations:
      required: true
  - type: dropdown
    id: i-did-my-homework
    attributes:
      label: I have searched for existing issues
      description: You confirm that you took the time to search for existing issues.
      options:
        - ""
        - "Yes"
    validations:
      required: true
