name: Continuous Integration
on:
  push:
    branches: main
  pull_request:
    branches: main
defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno task lint

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - deno
          - node
          - bun
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: actions/setup-node@v4
        if: matrix.runtime == 'node'
      - uses: oven-sh/setup-bun@v2
        if: matrix.runtime == 'bun'
      - run: npm ci
        if: matrix.runtime == 'node' || matrix.runtime == 'bun'
      - run: deno task test:${{ matrix.runtime }}

  publish:
    name: Publish
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno publish
