name: Continuous Integration
on:
  push:
    branches: main
  pull_request:
    branches: main
    paths-ignore:
      - ".devcontainer/**"
      - "**/*.md"
defaults:
  run:
    shell: bash

jobs:
  code:
    name: Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        task:
          - lint
          - test
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: rc
      - run: deno task ${{ matrix.task }}

  publish:
    name: Publish
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - code
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: rc
      - run: deno publish
