name: Stale
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-all-milestones: true
